version: "2.3"

services:
  db:
    image: postgres:14.8-alpine3.18
    volumes:
      - .docker/.volumes/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    networks:
      - zebrands
  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - zebrands
  app:
    build:
      context: .
      dockerfile: .docker/local.Dockerfile
    restart: always
    volumes:
      - .:/app/
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - "8080:8080"
    networks:
      - zebrands
    depends_on:
      - db
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    networks:
      - zebrands
  worker:
    build:
      context: .
      dockerfile: .docker/local.Dockerfile
    restart: always
    volumes:
      - .:/app/
    env_file: .env
    command: celery -A app worker -B --loglevel=info -Q celery,celery:1
    depends_on:
      - db
      - redis

networks:
  zebrands:
    driver: bridge
    name: zebrands

