# Generated by Django 4.2.4 on 2023-10-04 18:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="category",
            new_name="Brand",
        ),
    ]
