# Generated by Django 4.2.4 on 2023-10-04 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_rename_category_product_brand"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Brand",
            new_name="brand",
        ),
    ]
