# Generated by Django 4.2.4 on 2023-10-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_product_prince_product_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(unique=True),
        ),
    ]
